# Base configs
baseurl: ""
#baseurl: "" # Comment the above line and uncomment this to test the website locally
#youtube_urls: "/assets/yt.txt"

# UI configs
title: "Videos by Olga Alexeeva"
subtitle: "See the world through my eyes"
author: "Olga Alexeeva"
header:
  title: "Videos"
  subtitle: "by Olga Alexeeva"
footer:
  name: "Hey there, my name is Olga"
  bio: "Hello! I'm Olga, a passionate video editor from Germany, leveraging the transformative power of AI to create visually stunning and innovative videos. With a flair for blending creativity with technology, I specialize in bringing stories to life through the art of video editing, tailored to captivate a global audience."
social_urls:
  instagram: "https://www.instagram.com/oalfoxy/"
  youtube: "https://www.youtube.com/@olgaalexeeva"
  tiktok: "https://www.tiktok.com/@oalfoxy"
