# Base configs
baseurl: ""
#baseurl: "" # Comment the above line and uncomment this to test the website locally
#youtube_urls: "/assets/yt.txt"

# UI configs
title: "Videos by Oalfoxy"
subtitle: "See the world through my eyes"
author: "Olga Melnik"
header:
  title: "Videos"
  subtitle: "by Oalfoxy"
footer:
  name: "Olga Melnik"
  bio: "Hi there! My name is Olga. I am passionate AI-artist and video editor from Germany, leveraging the power of AI to create stunning and innovative videos. I specialize in bringing stories to life through the art of video editing, tailored to captivate global audience."
social_urls:
  instagram: "https://www.instagram.com/oalfoxy/"
  youtube: "https://www.youtube.com/@oalfoxy"
  tiktok: "https://www.tiktok.com/@oalfoxy"
  twitter: "https://x.com/oalfoxy"
  linkedin: "https://www.linkedin.com/in/oalfoxy"
  pinterest: "https://www.pinterest.de/oalfoxy/"
  etsy: "https://www.etsy.com/de-en/shop/OALstudio"
  email: "olga.alexeeva@oal-studio.de"
